service:
  name: cartman

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs8.10
  environment:
    GITHUB_ACCESS_TOKEN: <your_access_token>
    GITHUB_WEBHOOK_SECRET: <your_webhook_secret>

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: hello
